version: '3.8'

services:
  postgres:
    image: postgres:17.1
    container_name: ${POSTGRES_SERVER}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT}:5432"  # HOST_PORT:CONTAINER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
