name: Node.js CI for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}-${{ matrix.node-version }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ matrix.node-version }}-

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json') }}-${{ matrix.node-version }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ matrix.node-version }}-

    - name: Install dependencies
      run: npm install

    - name: Cache .next build files
      uses: actions/cache@v3
      with:
        path: .next
        key: ${{ runner.os }}-next-${{ hashFiles('**/package.json') }}-${{ matrix.node-version }}
        restore-keys: |
          ${{ runner.os }}-next-${{ matrix.node-version }}-

    - name: Build the project
      run: npm run build --if-present

    - name: Run tests
      run: npm test --if-present
